name: Push Test
on: [push]
jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: 2.6.3p62
            - name: Run bundle install
              run:
                    bundle install
            - name: Build and test with rspec
              run: bundle exec rspec spec
