name: Unit Tests for Tic-Tac-Toe
on: [push]
jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
              with:
                  ruby-version: 2.6.3
            - name: Run bundle install
              run: bundle install
            - name: Build and test with rspec
              run: bundle exec rspec spec
            - name: Run standard ruby linter
              run: bundle exec standardrb
